### ISSUE TITLE
에 네트워크 연결하고 Stable 밖에 뜨지 않네요...

### ISSUE THREAD

**Issue by readingsnail** [minacle/NetLive#1]
<img width="99" alt="2016-06-16 5 46 08" src="https://cloud.githubusercontent.com/assets/1904967/16110745/40077be6-33ea-11e6-9f07-e78bb0e10fb3.png">

10.11.6 베타(15G12a) 사용하고 있는데, IP나 그런게 하나도 안뜨고 저렇게 나오네요 ㄷㄷㄷ

**Comment by minacle** [comment]
심플을 추구했기 때문에, 기본적으로 문제가 있을 경우에만 문제가 있는 네트워크를 함께 표시하는 식으로 구현되어 있어요.
모든 옵션이 보고 싶으시면 옵션 키와 함께 클릭해보세요!
